# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-create-pre-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Expose Commit Data
      uses: rlespinasse/git-commit-data-action@v1
      
    - name: Zip the Build
      run: |
        cd /home/runner/work/MHW-Better-Matchmaking/MHW-Better-Matchmaking/BetterMatchmaking/bin/Release/net8.0-windows10.0.22621.0 
        zip -r BetterMatchmaking_${{ github.run_number }}_${{ env.GIT_COMMIT_SHORT_SHA }}.zip *
        
    - name: Create Build Release
      uses: ncipollo/release-action@v1.14.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: 0${{ github.run_number }}-${{ env.GIT_COMMIT_SHORT_SHA }}
        name: Build 0${{ github.run_number }} (${{ env.GIT_COMMIT_SHORT_SHA }})
        draft: false
        prerelease: true
        body: '## [Main Repo](https://github.com/GreenComfyTea/MHW-Better-Matchmaking) | [Commit Files](https://github.com/GreenComfyTea/MHW-Better-Matchmaking/tree/${{ env.GIT_COMMIT_SHA }})'
        token: ${{ secrets.NIGHTLY_TOKEN }}
        repo: MHW-Better-Matchmaking-Nightly
        artifacts: "/home/runner/work/MHW-Better-Matchmaking/MHW-Better-Matchmaking/BetterMatchmaking/bin/Release/net8.0-windows10.0.22621.0/BetterMatchmaking_${{ github.run_number }}_${{ env.GIT_COMMIT_SHORT_SHA }}.zip"
        
    - name: Update Latest Release
      uses: ncipollo/release-action@v1.14.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: latest
        name: Nightly 0${{ github.run_number }} (${{ env.GIT_COMMIT_SHORT_SHA }})
        draft: false
        allowUpdates: true
        removeArtifacts: true
        body: '## [Main Repo](https://github.com/GreenComfyTea/MHW-Better-Matchmaking) | [Commit Files](https://github.com/GreenComfyTea/MHW-Better-Matchmaking/tree/${{ env.GIT_COMMIT_SHA }}) | Ignore the date shown for the release. This is the latest build.'
        token: ${{ secrets.NIGHTLY_TOKEN }}
        repo: MHW-Better-Matchmaking-Nightly
        artifacts: "/home/runner/work/MHW-Better-Matchmaking/MHW-Better-Matchmaking/BetterMatchmaking/bin/Release/net8.0-windows10.0.22621.0/BetterMatchmaking_${{ github.run_number }}_${{ env.GIT_COMMIT_SHORT_SHA }}.zip"
